name: fakenoticications_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  flutter_riverpod: ^1.0.3
  flutter_local_notifications: ^9.4.0

flutter_native_splash:
  color: "#5e17eb"
  image: assets/偽 通 知.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/